### ISSUE TITLE
Use certbot docker image

### ISSUE THREAD

**Issue by katopz** [hamburml/docker-flow-letsencrypt#25]
Hi,

Maybe it's a good idea to use [certbot docker image](https://hub.docker.com/r/certbot/certbot/) instead of `curl` `certbot-auto` package while build?

Thanks

**Comment by hamburml** [comment]
Hey.

Last time I checked the certbot docker image it wasn't updated to the latest version and I wasn't sure if they upload a new image shorty after they release a new version. I also know of some issues on their github project regarding docker and I thought it's easier to install `certbot-auto` directly instead of using their image (and when their image isn't updated/working anymore this project is also not working anymore).

What do you say?

**Comment by katopz** [comment]
Hi,

At first I think It should be easier to update via  docker compose update policy, and usually docker hub should hook with github and will trigger auto build so it should be same (if they hook it right).

Anyway I still not sure which one is a good idea, I can think of 3 approaches here

1. Use Ubuntu base image (which is huge?) and curl certbot-auto package (like you did)
1. Dockerfile `FROM certbot/cerbot` and overlay it.
1. Dockerfile `FROM alpine` and compose like...
```yml
version: '3'
services:
  nginx-certbot:
    build: .
    container_name: nginx-certbot
    env_file: .env
    image: rabbotio/nginx-certbot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - etc-nginx-conf.d:/etc/nginx/conf.d
      - etc-ssl:/etc/ssl
      - var-www:/var/www
      - etc-letsencrypt:/etc/letsencrypt
      - var-log-letsencrypt:/var/log/letsencrypt
    depends_on:
      - nginx
      - certbot
    links:
      - nginx
      - certbot
    networks:
      - back
    deploy:
      mode: global # exactly one container per swarm node

  nginx:
    image: nginx:alpine
    container_name: nginx
    env_file: .env
    restart: on-failure
    networks:
      - back
    volumes:
      - etc-nginx-conf.d:/etc/nginx/conf.d
      - etc-ssl:/etc/ssl
      - var-www:/var/www
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: certbot
    env_file: .env
    environment:
      - DOMAIN=$DOMAIN
      - CERTBOT_EMAIL=$CERTBOT_EMAIL
      - ACME_WWWROOT=${ACME_WWWROOT:-/usr/share/nginx/html}
    networks:
      - back
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - var-log-letsencrypt:/var/log/letsencrypt

volumes:
  etc-nginx-conf.d:
  etc-ssl:
  var-www:
  etc-letsencrypt:
  var-log-letsencrypt:

networks:
  back:
```
(Just rough idea, not test yet and will need volume data container)

But it seem like `docker.sock` is a bad idea so I think I'll give up and use you approach instead.
Not sure you have an example `nginx` container trigger reload after renewal? (Yes, I'll use df)

Thanks!
