### ISSUE TITLE
Full stack example not working

### ISSUE THREAD

**Issue by nicoecheza** [hamburml/docker-flow-letsencrypt#41]
Hey, we have been trying to make this work but the example is not working properly.

It seems the Let's Encrypt container is not properly serving the `./well-known/acme-challenge` dir.

Here is the container's output:

```
Starting Docker Flow: Let's Encrypt
Docker Flow: Let's Encrypt started
We will use email@hi.com for certificate registration with certbot. This e-mail is used by Let's Encrypt when you lose the account and want to get it back.
Staging environment of Let's Encrypt is activated! The generated certificates won't be trusted. But you will not reach Let’s Encrypt's rate limits.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for domain.hi
Waiting for verification...
Cleaning up challenges

Failed authorization procedure. domain.hi (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://domain.hi/.well-known/acme-challenge/MOJDB6_a_sXYiYltms79f8Cd2mlaTU30nh-O449cOJs: Connection refused
Unable to verify domain ownership, we try again in 5 seconds.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for domain.hi
Waiting for verification...
Cleaning up challenges

Hello! renewAndSendToProxy runs. Today is Tue May  8 18:57:24 UTC 2018
/root/renewAndSendToProxy.sh: line 22: cd: /etc/letsencrypt/live/*/: No such file or directory
old certificates for  will be send to proxy
cat: cert.pem: No such file or directory
cat: chain.pem: No such file or directory
cat: privkey.pem: No such file or directory
HTTP/1.1 400 Bad Request
Date: Tue, 08 May 2018 18:57:24 GMT
Content-Length: 125
Content-Type: text/plain; charset=utf-8

{"Status":"NOK","Message":"Could not send distribute request to the following addresses: [ip1 ip2]","Certs":null}old certificates: proxy received .combined.pem
```

**Comment by hamburml** [comment]
Hi @nicoecheza,

sorry to hear that :/

What version of Docker Flow: Proxy and Docker Flow: Swarm Listener do you use? Did you create the `/etc/letsencrypt` folder before you started the service? Are your DNS-Settings correctly set (for example, can you ping your server with the domain you used?). Do you use ipv6 or ipv4?

**Comment by nicoecheza** [comment]
Hi,

**What version of Docker Flow: Proxy and Docker Flow: Swarm Listener do you use?**
Latest for both 

**Did you create the /etc/letsencrypt folder before you started the service?**
Yes

**Are your DNS-Settings correctly set (for example, can you ping your server with the domain you used?)**
Yes

**Do you use ipv6 or ipv4?**
ipv4, not sure about this one

**Comment by nicoecheza** [comment]
Also, we tried to create a `.well-kwown/acme-challenge/test.txt` directory inside the Let's Encrypt container to see if we can reach it (created it in several folders), but we failed. We are not sure where you are storing it since the container has no `--webroot` option and it also cleans everything up

**Comment by hamburml** [comment]
Thanks for your answer.

Currently, you need to use ipv4. Docker had some problems with ipv6 if I remember correctly.

What does your browser show if you try to reach your domain (via http)?

You won't find a folder where you can create a `.well-kwown/acme-challenge/test.txt` file because there is no webserver installed. `certbot-auto` uses the `standalone` setting (https://github.com/hamburml/docker-flow-letsencrypt/blob/v0.1.5/certbot.sh#L18), which starts it's own webserver only for the verification-process (https://certbot.eff.org/docs/using.html#standalone). 

The container is smaller in size this way. I just tried it with the latest DFP and DFSL versions and it worked (https://michael-hamburger.de/).

Can you please check your dns-settings again? If I remember correctly I once had the problem that I set `AAAA` records instead of `A` records.

**Comment by nicoecheza** [comment]
We actually have a cname: 
`new-swarm-testing.mural.co` => `nicoswarm.eastus.cloudapp.azure.com`

Do you think that can be a problem?

**Comment by hamburml** [comment]
CNAME should work but you need a A record for the CNAME target (which should be the cloudapp.azure.com url). See https://community.letsencrypt.org/t/having-issues-getting-certificates-with-cname-records/31481

I found https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-custom-domain-name-portal#add-an-a-record-for-your-custom-domain which should help you adding a A record for your azure-app.

I hope this helps.

PS: If I were you I would remove the CNAME and only use an A record for the beginning. If this works we could try adding the CNAME.

**Comment by nicoecheza** [comment]
Thanks for your replies 😍 

Changed it and it is now using an A record, but still no luck 😢, same error.

**Comment by hamburml** [comment]
Wait some minutes (or hours?) - DNS changes needs some time. DNS-Servers love caching :)

*edit*

BTW, it looks like Azure changes the public ips from time to time... https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-reserved-public-ip
So the A record could point to an ip-address which is (in some days?) not your server anymore.

**Comment by nicoecheza** [comment]
Ok nice. Will reach you again in a few hours.

**Comment by gvilarino** [comment]
Hi @hamburml ; I'm helping @nicoecheza in this one. Still not working here, either with an A record or a CNAME.

If we look at the proxy logs in debug mode, the verification request is being forwarded to the letsencrypt service (i.e.: the request matches the ACL) but it fails with the error provided by OP.

I have a question: in all your examples you always start the `DOMAIN_*` env var with an apex domain, followed by subdomains. It's not our case, and was wondering if this wouldn't work for a single, complete domain (e.g.: `DOMAIN_1=('my.domain.com')`)

Also, our stack configuration is almost exactly this one (just changing domain names):

```yaml
version: "3"

services:

  proxy:
    image: dockerflow/docker-flow-proxy
    deploy:
      replicas: 2
      placement:
        constraints: [node.hostname == manager-hostname]
    environment:
      - DEBUG=true
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  letsencrypt-companion:
    image: hamburml/docker-flow-letsencrypt:latest
    networks:
      - proxy
    environment:
      - DOMAIN_1=( 'new-swarm-testing.domain.com' )
      - CERTBOT_EMAIL=user@domain.com
      - PROXY_ADDRESS=proxy
      - CERTBOT_CRON_RENEW=('0 3 * * *' '0 15 * * *')
      - CERTBOTMODE=staging
    deploy:
      labels:
        - com.df.servicePath=/.well-known/acme-challenge
        - com.df.notify=true
        - com.df.port=80
      replicas: 1
      placement:
        constraints: [node.hostname == manager-hostname]

networks:
  proxy:
    external: true
``` 

Note that the `proxy` network is an `overlay` network

However, if I replace the `letsencrypt-companion` image with an image that answers `200` when getting a request under `/.well-known/acme-challenge` we actually do get a response, so it's not the proxy or the listener not working properly.

If we run the above stackfile with `docker stack deploy`, we consistently get:

```
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for new-swarm-testing.domain.com
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. new-swarm-testing.domain.com (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://new-swarm-testing.domain.com/.well-known/acme-challenge/aHKxoYOzbJdCZKkZ2jYQFCAXTJEzK18xn3qOxVbf7cY: Connection refused
```

Please feel free try this one by replacing `domain.com` with `michael-hamburger.de`; should work the same.
