### ISSUE TITLE
Regenerate certs after removing CERTBOTMODE="staging"?

### ISSUE THREAD

**Issue by Twansparant** [hamburml/docker-flow-letsencrypt#47]
Hi there,

First of all, great project! This saved me a lot of custom work setting up renewal scripts on my Docker droplet!

I was wundering what is the correct way of (re-)generating 'production' certificates after removing the `CERTBOTMODE="staging"` environment variable in the initial setup? 

If I don't do anything, it keeps on using the old 'staging' certificates in the daily crons:

```
Hello! renewAndSendToProxy runs. Today is Tue Jan 29 03:00:01 UTC 2019
old certificates for sub.domain.com will be send to proxy
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Date: Tue, 29 Jan 2019 03:00:01 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

old certificates: proxy received sub.domain.com.combined.pem

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/sub.domain.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/sub.domain.com/fullchain.pem expires on 2019-04-28 (skipped)
No renewals were attempted.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Docker Flow: Proxy DNS-Name: proxy
current folder name is: sub.domain.com
concat certificates for sub.domain.com
generated sub.domain.com.combined.pem
transmit sub.domain.com.combined.pem to proxy
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Date: Tue, 29 Jan 2019 03:06:34 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

proxy received sub.domain.com.combined.pem
/etc/letsencrypt will be backed up as backup-date-time.tar.gz. It's important to know that some files are symbolic links (inside this backup) and they need to be untared correctly.
Backup created, if you like download the /etc/letsencrypt/backup folder and store it on a safe place!

Thanks for using Docker Flow: Let's Encrypt and have a nice day!
```
If I check the letsencrypt folder `/etc/letsencrypt/live/sub.domain.com`, I can see that only the `sub.domain.com.combined.pem` was renewed:
```
Jan 28 13:55 cert.pem -> ../../archive/sub.domain.com/cert2.pem
Jan 28 13:55 chain.pem -> ../../archive/sub.domain.com/chain2.pem
Jan 28 13:55 fullchain.pem -> ../../archive/sub.domain.com/fullchain2.pem
Jan 28 13:55 privkey.pem -> ../../archive/sub.domain.com/privkey2.pem
Jan 28 10:54 README
Jan 29 03:06 sub.domain.com.combined.pem
```
If I check the backup folder `/etc/letsencrypt/backup` though, it seems it did pickup the change in the CERTBOTMODE:
```
Jan 28 10:57 backup-20190128_105708_UTC-"staging".tar.gz
Jan 28 13:57 backup-20190128_135745_UTC-"staging".tar.gz
Jan 28 15:01 backup-20190128_150146_UTC-staging.tar.gz
Jan 28 15:51 backup-20190128_155107_UTC-live.tar.gz
Jan 28 16:07 backup-20190128_160731_UTC-live.tar.gz
Jan 29 03:06 backup-20190129_030634_UTC-live.tar.gz
```

Should I just remove the contents of the `/etc/letsencrypt/` folder and wait till the next cron? Or is there a better way without breaking anything?

Thanks in advance!

**Comment by hamburml** [comment]
Hi and thanks for using Docker Flow: Let's Encrypt!

Great find! Certbot looks at the staging-certificates and knows that they are still valid. That the certificate authority who signed the certificates is untrusted doesn't matter to certbot. The easiest way is to close the container, remove the /etc/letsencrypt folder and recreate a new empty one, restart the container and remove the staging-mode.

The newly created certificate should be signed by the trusted certificate authority and therefore trusted in browsers.

*edit*

https://community.letsencrypt.org/t/certbot-how-can-i-renew-if-staging-certs-exist-but-i-want-production-certs/46472/9

Instead of `--staging` I could use `--dry-run` which also tests the certificate creationg with staging-environment but doesn't store the certificates. Looks like there is a lot to improve :)

**Comment by Twansparant** [comment]
Thanks!
I'm getting a **rate-limit** error now, probably because I re-created the empty `/etc/letsencrypt/` folder when the container was already restarted, so I guess I have to wait till the next cron, but that's okay.
```
An unexpected error occurred:
There were too many requests of a given type :: Error finalizing order :: too many certificates already issued for exact set of domains: sub.domain.com,www.sub.domain.com: see https://letsencrypt.org/docs/rate-limits/
```
Thanks for your help!

**Comment by hamburml** [comment]
The rate-limit error means that you have hit one of Let's Encrypt's [limits](https://letsencrypt.org/docs/rate-limits/).

It's likely that it's the number of certificate creations or accounts per ip address. I am sorry but it looks like that starting the container without staging mode but having staged certificates in `/etc/letsencrypt/` does count as a "certificate renewal".

According to their docs they use a sliding window and you need to wait 7 days since the first certificate creation was finished (I have no idea if that is a grammatically correct sentence). For example you removed the staging mode yesterday, 28.01.2019, it will be resetted on 04.02.2019.

Sorry :(

**Comment by Twansparant** [comment]
> I am sorry but it looks like that starting the container without staging mode but having staged certificates in `/etc/letsencrypt/` does count as a "certificate renewal".

No need to be sorry, it's not your limit :)
I did remove the staged certificates before restarting the container, just didn't create the empty one. 
Just have to wait then I guess, thanks!

**Comment by hamburml** [comment]
But now you have created an empty `/etc/letsencrypt` folder on your host which is mounted to the container?

**Comment by Twansparant** [comment]
> But now you have created an empty `/etc/letsencrypt` folder on your host which is mounted to the container?

Yes and after I have done that I got the rate-limit right away.
I did use a different docker image before this and that already generated LE production certificates a few days ago, so I might just have to wait...

**Comment by Twansparant** [comment]
Hmm, the 15:00 cron job gives me this error now:
Should I empty the `/etc/letsencrypt` folder again?

```
Hello! renewAndSendToProxy runs. Today is Tue Jan 29 15:00:01 UTC 2019
old certificates for root will be send to proxy
HTTP/1.1 400 Bad Request
Date: Tue, 29 Jan 2019 15:00:01 GMT
Content-Length: 127
Content-Type: text/plain; charset=utf-8

{"Status":"NOK","Message":"Could not send distribute request to the following addresses: [10.0.4.167 10.0.4.161]","Certs":null}old certificates: proxy received root.combined.pem

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

No renewals were attempted.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Docker Flow: Proxy DNS-Name: proxy
current folder name is: root
concat certificates for root
generated root.combined.pem
transmit root.combined.pem to proxy
HTTP/1.1 400 Bad Request
Date: Tue, 29 Jan 2019 15:02:36 GMT
Content-Length: 127
Content-Type: text/plain; charset=utf-8

{"Status":"NOK","Message":"Could not send distribute request to the following addresses: [10.0.4.167 10.0.4.161]","Certs":null}proxy received root.combined.pem
/etc/letsencrypt will be backed up as backup-date-time.tar.gz. It's important to know that some files are symbolic links (inside this backup) and they need to be untared correctly.
Backup created, if you like download the /etc/letsencrypt/backup folder and store it on a safe place!

Thanks for using Docker Flow: Let's Encrypt and have a nice day!
```

**EDIT**: When I stop the container in my service stack and remove the /etc/letsencrypt folder, I think it's already restarting it resulting in error...

**EDIT 2**: When I completely remove my stack with `docker stack rm mystack` then remove and re-create the `/etc/letsencrypt` folder and redeploy my stack it works!
Now my production certificates are generated without rate-limits error!

**Comment by hamburml** [comment]
Oh, you are using a compose file! Docker should automatically restart the container, you are right.

Lovely that it works <3

**Comment by Twansparant** [comment]
Sorry I have to re-open this, not completely sure if it's related, but only 1 of the 2 domain entries were successfully validated and generated. Right now only the `www.sub.domain.com` has a valid certificate, and the `sub.domain.com` hasn't. I checked the DNS and they both resolve to the same IP.

My service stack looks like this:

```
  letsencrypt-companion:
    image: hamburml/docker-flow-letsencrypt:latest
    networks:
      - proxy
    environment:
      - DOMAIN_1=('sub.domain.com' 'www.sub.domain.com')
      - CERTBOT_EMAIL=hello@world.com
      - PROXY_ADDRESS=proxy
      - CERTBOT_CRON_RENEW=('0 3 * * *' '0 15 * * *')
    volumes:
          - /etc/letsencrypt:/etc/letsencrypt
    deploy:
      replicas: 1
      labels:
        - com.df.servicePath=/.well-known/acme-challenge
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=80
      placement:
        constraints: [node.id == my_master_node_id]
```

That should be ok right?
To force a regeneration of the certificates, should I follow the same steps again?

1) Remove my stack
2) Remove and create new empty `/etc/letsencrypt` folder
3) Deploy me stack

Thanks!

**Comment by hamburml** [comment]
Yes, this is correct. And yeah, that's how you can force a regeneration. Before you do that:

Could you please give me your real url? After I answered that I got it you can simply edit the comment. I would like to see the certificate stats which are shown in chrome/firefox. 

For example:

![image](https://user-images.githubusercontent.com/7239350/52062388-b7b26f00-2570-11e9-86bd-90f5f44b30c0.png)

**Comment by Twansparant** [comment]
Sure, the real url is:
[https://www.staging.thrillseeker.io](https://www.staging.thrillseeker.io) & [https://staging.thrillseeker.io](https://staging.thrillseeker.io)
The last one has an **ERR_SSL_VERSION_INTERFERENCE** error in chrome

**Comment by hamburml** [comment]
Got it, thanks!

It's correct that only one folder is created, one certificate can be valid for more than one sub-domains. To be honest, I always used a full domain as first parameter and after that only sub-domains. Maybe that's the reason. I'll check that on my server and come back to you in some hours. Feel free to remove the stack, clear the folder (or backup it), and recreate the stack.

Sorry!

**Comment by Twansparant** [comment]
Thanks!
I understand, but the full domain will be hosted on a different droplet, so I can't add that as the first parameter in this case.

**Comment by hamburml** [comment]
If it's important you could create two lets encrypt companions, one for `sub.domain.com`, the other for `www.sub.domain.com`. But that should only be a quick and dirty solution.

As said, I will reply in some hours again.

**Comment by hamburml** [comment]
Could it be that the `www.sub.domain.com` does only redirect to your `sub.domain.com` and does not directly point to the ip? BTW: the www is a subdomain. For example a DNS CNAME type?

*edit*

If I try to ping your `www.sub.domain.com` (the real one, not that example) I get answers from `sub.domain.com`. If I ping my current test-example `www.haha.michael-hamburger.de` I get answers from `www.haha.michael-hamburger.de`.

*edit2*

If I use https://mxtoolbox.com/SuperTool.aspx, set it to DNS lookup and use your `www.sub.domain.com` I see an A entry to `sub.domain.com`. If I use that same tool for `www.haha.michael-hamburger.de` I see an A entry for `www.haha.michael-hamburger.de`.

It works on my end.

https://www.haha.michael-hamburger.de/
https://haha.michael-hamburger.de/

```
docker service create --name letsencrypt-companion \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.servicePath=/.well-known/acme-challenge \
    --label com.df.port=80 \
    -e DOMAIN_1="('www.haha.michael-hamburger.de' 'haha.michael-hamburger.de')"\
    -e CERTBOT_EMAIL="xxx" \
    -e PROXY_ADDRESS="proxy" \
    -e CERTBOT_CRON_RENEW="('0 3 * * *' '0 15 * * *')"\
    --network proxy \
    --mount type=bind,source=/etc/letsencrypt,destination=/etc/letsencrypt \
    --constraint 'node.id==xxx' \
    --replicas 1 hamburml/docker-flow-letsencrypt:latest
```

![image](https://user-images.githubusercontent.com/7239350/52068857-cb180700-257d-11e9-9a49-b1ddb3f4df7f.png)

Both sub-domains, one certificate.

**Comment by Twansparant** [comment]
Yup that is correct, the www is a CNAME record.
Normally that should work with Letsencrypt certificates? So I should change the **CNAME** to an **A** record right?

Furthermore; is there a setting where I can redirect the www. domain to the non-www domain?

Thanks for your time, appreciate it!

**Comment by hamburml** [comment]
I haven't used CNAME records before, so I am not sure. If you change it to an A record (hopefulle the TTL isn't set too high, DNS changes can take some minutes) and recreate the certificate (remove stack, clear /etc/letsencrypt, recreate stack) it should work.

I think you can use the [redirectFromDomain](https://proxy.dockerflow.com/usage/) parameter. Here is an example https://github.com/vfarcic/docker-flow-proxy/issues/373 But I am not sure, domain redirection should be a feature from Docker Flow itself.

**Comment by Twansparant** [comment]
Hmm that is strange...
Changing the **CNAME** to an **A** record didn't make any difference I'm afraid.
After re-creating my stack and certificates I still get the following error for the non-www domain:

```
Starting Docker Flow: Let's Encrypt
Docker Flow: Let's Encrypt started
We will use hello@mydomain.com for certificate registration with certbot. This e-mail is used by Let's Encrypt when you lose the account and want to get it back.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for sub.domain.com
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. sub.domain.com (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://sub.domain.com/.well-known/acme-challenge/CKTsiKQTXGxJwYl9YUFUOMWySt7R1oeZSbXa6BRlz50: Connection refused
Unable to verify domain ownership, we try again in 5 seconds.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for sub.domain.com
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. sub.domain.com (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://sub.domain.com/.well-known/acme-challenge/kjN0RxKi5Dx4IdKiA7wjcs9WLWSGyJ2r5EGOomWy_TI [159.65.201.44]: 503
Unable to verify domain ownership, we try again in 5 seconds.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for sub.domain.com
Waiting for verification...
Cleaning up challenges
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for www.sub.domain.com
Waiting for verification...
Cleaning up challenges
Domain www.sub.domain.com successfully validated

Use certbot-auto certonly --no-self-upgrade --no-bootstrap --standalone --non-interactive --expand --keep-until-expiring --email hello@mydomain.com --agree-tos --preferred-challenges http-01 --rsa-key-size 4096 --redirect --hsts --staple-ocsp
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for www.sub.domain.com
Waiting for verification...
Cleaning up challenges
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/www.sub.domain.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/www.sub.domain.com/privkey.pem
   Your cert will expire on 2019-05-02. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot-auto
   again. To non-interactively renew *all* of your certificates, run
   "certbot-auto renew"
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

Hello! renewAndSendToProxy runs. Today is Fri Feb  1 08:31:41 UTC 2019
old certificates for www.sub.domain.com will be send to proxy
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Date: Fri, 01 Feb 2019 08:31:41 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

old certificates: proxy received www.sub.domain.com.combined.pem
Saving debug log to /var/log/letsencrypt/letsencrypt.log
```

Seems like the `/.well-known/acme-challenge/` service path is not resolved for the non-www domain?

**Comment by hamburml** [comment]
Please show the full stack compose file, with creation of docker flow proxy and swarm listener.

**Comment by Twansparant** [comment]
Sure thing!

```yaml
version: '3.7'

services:
  # Docker Flow Proxy
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  # Let's Encrypt Companion
  letsencrypt-companion:
    image: hamburml/docker-flow-letsencrypt:latest
    networks:
      - proxy
    environment:
      - DOMAIN_1=('sub.domain.com' 'www.sub.domain.com')
      - CERTBOT_EMAIL=hello@mydomain.com
      - PROXY_ADDRESS=proxy
      - CERTBOT_CRON_RENEW=('0 3 * * *' '0 15 * * *')
      # - CERTBOTMODE="staging" # uncomment for debugging
    volumes:
          - /etc/letsencrypt:/etc/letsencrypt
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/.well-known/acme-challenge
        - com.df.port=80
      placement:
        constraints: [node.id == xxxxxxxxxxxxxxxxxxxxxxxxx]

  # Frontend app
  client:
    build:
      context: .
      dockerfile: ./client/build/production/Dockerfile
    image: "${CI_REGISTRY_IMAGE}/client-${CI_COMMIT_REF_SLUG}"
    restart: unless-stopped
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=3000
    environment:
      - NODE_ENV=production
    command: npm run start

networks:
  proxy:
    external: true
```

**EDIT**: Side note: I can't find any `/.well-known/acme-challenge/` folder anywhere? Does the `Cleaning up challenges` task remove this folder again?
If I visit the url of this challenge I get a Docker Flow Proxy 503 error: 
```
Docker Flow Proxy: 503 Service Unavailable
```

**Comment by hamburml** [comment]
The `/.well-known/acme-challenge` is not a real folder. It's part of a HTTP-request, which the running certbot application inside the docker container answers. But the certbot application is only answering this HTTP-request if it started the signing procedure, which it does when for example cronjob runs (or the container is started anew).

Could you please try to use `dockerflow/docker-flow-proxy` and `dockerflow/docker-flow-swarm-listener` instead of `vfarcic`. He is the one who started to develop Docker Flow and Docker Flow: Swarm Listener. He moved the repository to https://github.com/docker-flow/docker-flow-proxy

**Comment by Twansparant** [comment]
> Could you please try to use `dockerflow/docker-flow-proxy` and `dockerflow/docker-flow-swarm-listener` instead of `vfarcic`.

Done, but exact same error...
Super weird!

**Comment by hamburml** [comment]
Could you please remove the `www.sub.domain.com` and only try the `sub.domain.com`?

*edit*

Do you have any ideas @thomasjpfan @vfarcic? One subdomain can be reached, the other can't. A record is set for both subdomains.

**Comment by Twansparant** [comment]
> Could you please remove the `www.sub.domain.com` and only try the `sub.domain.com`?

Done, but no dice either:
```
Failed authorization procedure. sub.domain.com (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://sub.domain.com/.well-known/acme-challenge/abRJ48gWlUXR_UXE1v1kqBxqs9ycGsyU82Xs4a4ycdo: Connection refused
```
Could it be a timing issue? Maybe the `proxy` or `swarm-listener`is not ready yet when `letsencrypt-companion` is trying to resolve the first domain?

I added the **depends_on** config in `letsencrypt-companion`:
```yaml
    depends_on:
      - proxy
      - swarm-listener
```
But that doesn't help either

**Comment by hamburml** [comment]
Could be.

You could create everything via `docker service create` commands and wait till proxy and swarm-listener is started. After that create the swarm-listener. That's how I did it yesterday.

**Comment by Twansparant** [comment]
Ah that's interesting!
If I add a fake (sub) domain as the first entry:
```
- DOMAIN_1=('sub.not-my-domain.com' 'sub.my-domain.com' 'www.sub.my-domain.com')
```
It will try to re-validate it 5 times:
```
Unable to verify domain ownership, we try again in 5 seconds.
```
But by the time it reaches domain entry 2, it does validate my **sub.my-domain.com** correctly and generates it!

So definitely a timing-issue!
I added `client' to the depends_on config but that's not enough I'm afraid...

```yaml
    depends_on:
      - proxy
      - swarm-listener
      - client
```
I think I need someting like [wait-for-it](https://github.com/vishnubob/wait-for-it) or set a timeout on your `/root/servicestart` command...

Thanks for all your help, really appreciate it!

**Comment by hamburml** [comment]
Great find!

If you like you can create two compose files. One for the swarm-listener and the client and another for letsencrypt. Use the first compose file for proxy and swarm-listener, wait some time and than use the second file for the letsencrypt-container. When the letsencrypt-container can create the certificates, it will be reachable in the future, too. (or don't use compose files at all and use the `docker service create` command. You only need to initialize the docker swarm and services once. You could add this to a bash script which waits some seconds before the letsencrypt-container is started).

Afaik there is no "wait-n-seconds" command build in docker compose. The `depends_on` only waits till the container is running but not till the application which runs inside the container is ready/finished.

I don't think it's wise to add a timeout directly in this container. When the container starts it's necessary that the whole Docker Flow environment is already working.

**Comment by Twansparant** [comment]
> If you like you can create two compose files. One for the swarm-listener and the client and another for letsencrypt. Use the first compose file for proxy and swarm-listener, wait some time and than use the second file for the letsencrypt-container. When the letsencrypt-container can create the certificates, it will be reachable in the future, too. (or don't use compose files at all and use the `docker service create` command. You only need to initialize the docker swarm and services once. You could add this to a bash script which waits some seconds before the letsencrypt-container is started).

Thanks for all your suggestions!
I ended up making my own **Dockerfile** for `docker-flow-letsencrypt`:

```
FROM hamburml/docker-flow-letsencrypt:latest

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY ./letsencrypt/build/wait-for-it.sh /usr/src/app/wait-for-it.sh
RUN ["chmod", "+x", "/usr/src/app/wait-for-it.sh"]
```
I use [wait-for-it](https://github.com/vishnubob/wait-for-it) for the shell script.
Then in my **docker-compose** file I override your Dockerfile **command**:

```yaml
  # Docker Flow Let's Encrypt Companion
  letsencrypt-companion:
    build:
      context: .
      dockerfile: ./letsencrypt/build/production/Dockerfile
    image: "${CI_REGISTRY_IMAGE}/letsencrypt-${CI_COMMIT_REF_SLUG}"
    networks:
      - proxy-network
    depends_on:
      - client
    environment:
      - DOMAIN_1=('sub.my-domain.com' 'www.sub.my-domain.com')
      - CERTBOT_EMAIL=hello@my-domain.com
      - PROXY_ADDRESS=proxy
      - CERTBOT_CRON_RENEW=('0 3 * * *' '0 15 * * *')
    volumes:
          - /etc/letsencrypt:/etc/letsencrypt
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/.well-known/acme-challenge
        - com.df.port=80
      placement:
        constraints: [node.id == xxxxxxxxxxxxxxxxxx]
    command: /usr/src/app/wait-for-it.sh client:3000 -- /root/servicestart
```
And now the logs look like this:

```console
wait-for-it.sh: waiting 15 seconds for client:3000
wait-for-it.sh: timeout occurred after waiting 15 seconds for client:3000
Starting Docker Flow: Let's Encrypt
Docker Flow: Let's Encrypt started
We will use hello@my-domain.com for certificate registration with certbot. This e-mail is used by Let's Encrypt when you lose the account and want to get it back.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for sub.my-domain.com
Waiting for verification...
Cleaning up challenges
Domain sub.my-domain.com successfully validated
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for www.sub.my-domain.com
Waiting for verification...
Cleaning up challenges
Domain www.sub.my-domain.com successfully validated

Use certbot-auto certonly --no-self-upgrade --no-bootstrap --standalone --non-interactive --expand --keep-until-expiring --email hello@my-domain.com --agree-tos --preferred-challenges http-01 --rsa-key-size 4096 --redirect --hsts --staple-ocsp
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for sub.my-domain.com
http-01 challenge for www.sub.my-domain.com
Waiting for verification...
Cleaning up challenges
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/sub.my-domain.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/sub.my-domain.com/privkey.pem
   Your cert will expire on 2019-05-02. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot-auto
   again. To non-interactively renew *all* of your certificates, run
   "certbot-auto renew"
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

Hello! renewAndSendToProxy runs. Today is Fri Feb  1 15:30:21 UTC 2019
old certificates for sub.my-domain.com will be send to proxy
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Date: Fri, 01 Feb 2019 15:30:22 GMT
Content-Length: 0

old certificates: proxy received sub.my-domain.com.combined.pem
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/sub.my-domain.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not yet due for renewal

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/sub.my-domain.com/fullchain.pem expires on 2019-05-02 (skipped)
No renewals were attempted.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Docker Flow: Proxy DNS-Name: proxy
current folder name is: sub.my-domain.com
concat certificates for sub.my-domain.com
generated sub.my-domain.com.combined.pem
transmit sub.my-domain.com.combined.pem to proxy
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Date: Fri, 01 Feb 2019 15:30:25 GMT
Content-Length: 0

proxy received sub.my-domain.com.combined.pem
/etc/letsencrypt will be backed up as backup-date-time.tar.gz. It's important to know that some files are symbolic links (inside this backup) and they need to be untared correctly.
Backup created, if you like download the /etc/letsencrypt/backup folder and store it on a safe place!

Thanks for using Docker Flow: Let's Encrypt and have a nice day!
```

Thanks again!
